from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, content: str) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")


def replace_exact(path: str, old: str, new: str, *, expected: int | None = 1) -> None:
    text = read(path)
    count = text.count(old)
    if expected is not None and count != expected:
        raise RuntimeError(f"{path}: expected {expected} occurrences, found {count}: {old!r}")
    if count == 0:
        raise RuntimeError(f"{path}: missing replacement target: {old!r}")
    write(path, text.replace(old, new))


def replace_if_present(path: str, old: str, new: str) -> int:
    text = read(path)
    count = text.count(old)
    if count:
        write(path, text.replace(old, new))
    return count


def replace_regex(path: str, pattern: str, replacement: str, *, expected: int = 1) -> None:
    text = read(path)
    next_text, count = re.subn(pattern, replacement, text, flags=re.S)
    if count != expected:
        raise RuntimeError(f"{path}: expected {expected} regex replacements, found {count}: {pattern}")
    write(path, next_text)


# ---------------------------------------------------------------------------
# Toolchains and pinned GitHub Actions.
# ---------------------------------------------------------------------------
CHECKOUT_OLD = "actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0"
CHECKOUT_NEW = "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1"
SETUP_NODE_OLD = "actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0"
SETUP_NODE_NEW = "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0"
UPLOAD_ARTIFACT_V6 = "actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0"
UPLOAD_ARTIFACT_V7 = "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1"

for workflow in sorted((ROOT / ".github" / "workflows").glob("*.yml")):
    text = workflow.read_text(encoding="utf-8")
    text = text.replace(CHECKOUT_OLD, CHECKOUT_NEW)
    text = text.replace(SETUP_NODE_OLD, SETUP_NODE_NEW)
    text = text.replace(UPLOAD_ARTIFACT_V6, UPLOAD_ARTIFACT_V7)
    text = text.replace('deno-version: "2.9.3"', 'deno-version: "2.9.5"')
    text = text.replace("-Version 3.44.8", "-Version 3.47.0")
    workflow.write_text(text, encoding="utf-8", newline="\n")

# Source/toolchain floors. Dart remains a broad >=3.12.2,<4 constraint; the
# Flutter SDK selected below supplies the compatible stable Dart SDK.
for path in ["pubspec.yaml", "README.md", "CONTRIBUTING.md", "docs/development/getting-started.md"]:
    replace_if_present(path, 'flutter: ">=3.44.7"', 'flutter: ">=3.47.0"')
    replace_if_present(path, "Flutter 3.44.7", "Flutter 3.47.0")
    replace_if_present(path, "Flutter >= 3.44.7", "Flutter >= 3.47.0")

# Keep every Edge Function on the same reviewed Supabase JS line. Lockfiles are
# regenerated by the temporary workflow after this source edit.
for deno_json in sorted(ROOT.rglob("deno.json")):
    text = deno_json.read_text(encoding="utf-8")
    text = text.replace("npm:@supabase/supabase-js@2.110.8", "npm:@supabase/supabase-js@2.112.3")
    deno_json.write_text(text, encoding="utf-8", newline="\n")

# GitHub Actions source policy: keep only commits actually used by current
# workflows. Owner patterns do not change, only reviewed release identities.
policy_path = "tool/github-actions-policy.mjs"
policy = read(policy_path)
policy = policy.replace(
    "  'actions/checkout': Object.freeze({\n    d23441a48e516b6c34aea4fa41551a30e30af803: 'v6.1.0',\n  }),",
    "  'actions/checkout': Object.freeze({\n    '3d3c42e5aac5ba805825da76410c181273ba90b1': 'v7.0.1',\n  }),",
)
policy = policy.replace(
    "  'actions/setup-node': Object.freeze({\n    '249970729cb0ef3589644e2896645e5dc5ba9c38': 'v6.5.0',\n  }),",
    "  'actions/setup-node': Object.freeze({\n    '820762786026740c76f36085b0efc47a31fe5020': 'v7.0.0',\n  }),",
)
policy = policy.replace(
    "  'actions/upload-artifact': Object.freeze({\n    '043fb46d1a93c77aae656e7c1c64a875d1fc6a0a': 'v7.0.1',\n    b7c566a772e6b6bfb58ed0dc250532a479d7789f: 'v6.0.0',\n    ea165f8d65b6e75b540449e92b4886f43607fa02: 'v4.6.2',\n  }),",
    "  'actions/upload-artifact': Object.freeze({\n    '043fb46d1a93c77aae656e7c1c64a875d1fc6a0a': 'v7.0.1',\n  }),",
)
if CHECKOUT_OLD.split("@", 1)[1].split(" ", 1)[0] in policy or SETUP_NODE_OLD.split("@", 1)[1].split(" ", 1)[0] in policy:
    raise RuntimeError("github-actions policy still contains retired checkout/setup-node pins")
write(policy_path, policy)

# Release-workflow source tests include literal pin fixtures; keep them aligned
# with the active policy without weakening any negative cases.
for path in ["tool/release-workflows.test.mjs"]:
    text = read(path)
    text = text.replace(CHECKOUT_OLD, CHECKOUT_NEW)
    text = text.replace(SETUP_NODE_OLD, SETUP_NODE_NEW)
    text = text.replace(UPLOAD_ARTIFACT_V6, UPLOAD_ARTIFACT_V7)
    text = text.replace("d23441a48e516b6c34aea4fa41551a30e30af803", "3d3c42e5aac5ba805825da76410c181273ba90b1")
    text = text.replace("249970729cb0ef3589644e2896645e5dc5ba9c38", "820762786026740c76f36085b0efc47a31fe5020")
    write(path, text)

# ---------------------------------------------------------------------------
# Drift: schema 25 is the first-production local compatibility floor.
# Preserve the current schema and all live sync tables/triggers; delete only
# conversion code whose sole purpose was upgrading unreleased schemas 1..24.
# ---------------------------------------------------------------------------
path = "lib/src/core/database/app_database.dart"
text = read(path)
text = text.replace(
    "  static const currentSchemaVersion = 25;\n",
    "  static const currentSchemaVersion = 25;\n"
    "  static const minimumSupportedSchemaVersion = 25;\n",
    1,
)
start = text.index("  @override\n  MigrationStrategy get migration => MigrationStrategy(")
before_marker = "    beforeOpen:"
before = text.index(before_marker, start)
new_migration_prefix = """  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
    },
    onUpgrade: (_, from, to) async {
      if (from < minimumSupportedSchemaVersion) {
        throw UnsupportedError(
          'HomePilot local database schema $from predates the first-production '
          'baseline $minimumSupportedSchemaVersion. Prelaunch databases are '
          'intentionally not migrated.',
        );
      }
      throw StateError(
        'No HomePilot local database migration is defined from schema $from to $to.',
      );
    },
    beforeOpen:"""
text = text[:start] + new_migration_prefix + text[before + len(before_marker):]
historical_start = text.index("  Future<void> _upgradeToV2")
seed_start = text.index("  Future<void> _seedSyncRuntime()", historical_start)
text = text[:historical_start] + text[seed_start:]
if "_upgradeToV" in text:
    raise RuntimeError("historical Drift upgrade functions remain after baseline collapse")
if "jsonDecode(" not in text and "jsonEncode(" not in text:
    text = text.replace("import 'dart:convert';\n", "")
write(path, text)

write(
    "test/database_migration_test.dart",
    """import 'dart:io';

import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:homepilot/src/core/database/app_database.dart';

void main() {
  test('fresh installs create the schema-25 production baseline', () async {
    final file = File(
      '${Directory.systemTemp.path}/homepilot_fresh_baseline_'
      '${DateTime.now().microsecondsSinceEpoch}.sqlite',
    );
    final db = AppDatabase(executor: NativeDatabase(file));
    try {
      await db.customSelect('SELECT 1').get();
      final version = await db.customSelect('PRAGMA user_version').getSingle();
      expect(
        version.read<int>('user_version'),
        AppDatabase.currentSchemaVersion,
      );
      expect(
        AppDatabase.minimumSupportedSchemaVersion,
        AppDatabase.currentSchemaVersion,
      );

      final tables = await db
          .customSelect(
            "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name",
          )
          .get();
      final names = tables.map((row) => row.read<String>('name')).toSet();
      expect(
        names,
        containsAll(<String>{
          'offline_mutation_queue',
          'reminder_schedule_snapshot',
          'sync_account',
          'sync_cursors',
          'sync_media_cleanup',
          'sync_runtime',
          'sync_shadows',
          'notification_reconciliation_requests',
        }),
      );
    } finally {
      await db.close();
      if (await file.exists()) await file.delete();
    }
  });

  test('prelaunch local schemas are rejected instead of migrated', () async {
    final file = File(
      '${Directory.systemTemp.path}/homepilot_prelaunch_schema_'
      '${DateTime.now().microsecondsSinceEpoch}.sqlite',
    );
    final original = AppDatabase(executor: NativeDatabase(file));
    await original.customSelect('SELECT 1').get();
    await original.customStatement(
      'PRAGMA user_version = ${AppDatabase.minimumSupportedSchemaVersion - 1}',
    );
    await original.close();

    final reopened = AppDatabase(executor: NativeDatabase(file));
    try {
      await expectLater(
        reopened.customSelect('SELECT 1').get(),
        throwsA(
          predicate<Object>(
            (error) => error.toString().contains('predates the first-production'),
          ),
        ),
      );
    } finally {
      try {
        await reopened.close();
      } catch (_) {
        // Opening is intentionally rejected before normal database startup.
      }
      if (await file.exists()) await file.delete();
    }
  });
}
""",
)

# ---------------------------------------------------------------------------
# Backup/restore: format 2 + Drift schema 25 are the production compatibility
# floor. All archive/path/hash/integrity/rollback protections remain unchanged.
# ---------------------------------------------------------------------------
path = "lib/src/core/services/backup_service.dart"
text = read(path)
text = text.replace("const _minimumFormatVersion = 1;", "const _minimumFormatVersion = 2;", 1)
text, removed_schema_lists = re.subn(
    r"\nconst _schemaOneTables = \[.*?\];\n\nconst _schemaTwoTables = \[.*?\];\n",
    "\n",
    text,
    count=1,
    flags=re.S,
)
if removed_schema_lists != 1:
    raise RuntimeError("backup_service.dart: could not remove legacy schema table inventories")
manifest_guard = """    if (manifestSchemaVersion > db.schemaVersion) {
      throw const BackupException(
        'Backup was created by a newer database schema. Update HomePilot before restoring this file.',
      );
    }
"""
replacement_guard = """    if (manifestSchemaVersion < AppDatabase.minimumSupportedSchemaVersion) {
      throw const BackupException(
        'Backup database schema predates the first production HomePilot baseline and is not supported.',
      );
    }
    if (manifestSchemaVersion > db.schemaVersion) {
      throw const BackupException(
        'Backup was created by a newer database schema. Update HomePilot before restoring this file.',
      );
    }
"""
if manifest_guard not in text:
    raise RuntimeError("backup_service.dart: manifest schema guard changed unexpectedly")
text = text.replace(manifest_guard, replacement_guard, 1)
effective_guard = """      if (effectiveSchema > db.schemaVersion) {
        throw const BackupException(
          'Backup database is newer than this app. Update HomePilot before restoring.',
        );
      }

      final requiredTables = _requiredTablesForSchema(effectiveSchema);
"""
replacement_effective_guard = """      if (effectiveSchema < AppDatabase.minimumSupportedSchemaVersion) {
        throw const BackupException(
          'Backup database schema predates the first production HomePilot baseline and is not supported.',
        );
      }
      if (effectiveSchema > db.schemaVersion) {
        throw const BackupException(
          'Backup database is newer than this app. Update HomePilot before restoring.',
        );
      }

      final requiredTables = _currentSchemaTables;
"""
if effective_guard not in text:
    raise RuntimeError("backup_service.dart: effective schema guard changed unexpectedly")
text = text.replace(effective_guard, replacement_effective_guard, 1)
text = text.replace("_migrateExtractedDatabase", "_openValidatedExtractedDatabase")
text, required_fn_count = re.subn(
    r"\nList<String> _requiredTablesForSchema\(int schemaVersion\) \{.*?\n\}\n\nbool _tableExists",
    "\nbool _tableExists",
    text,
    count=1,
    flags=re.S,
)
if required_fn_count != 1:
    raise RuntimeError("backup_service.dart: legacy schema selection helper was not removed")
text = text.replace(
    """      final warnings = <String>[
        if (formatVersion < _currentFormatVersion)
          'This is an older backup format. HomePilot will migrate it during restore.',
        ..._readStringList(manifest, 'warnings'),
        ...summary.warnings,
      ];
""",
    """      final warnings = <String>[
        ..._readStringList(manifest, 'warnings'),
        ...summary.warnings,
      ];
""",
    1,
)
write(path, text)

path = "test/backup_service_test.dart"
text = read(path)
text = text.replace("import 'package:sqlite3/sqlite3.dart';\n", "")
start = text.index("    test('rejects tampered checksum and newer schema backups'")
end = text.index("  });\n}\n\nFuture<AppDatabase>", start)
new_tests = """    test(
      'rejects tampered checksum and unsupported format/schema backups',
      () async {
        final db = await _openDatabase(docs, databases);
        await _seedRealisticData(db, root);
        final service = ZipBackupService(db);
        final backupPath = await service.exportBackup();

        final tamperedChecksum = await _tamperBackup(
          backupPath,
          root,
          mutateDatabase: true,
        );
        final newerSchema = await _tamperBackup(
          backupPath,
          root,
          manifestUpdates: {'schemaVersion': db.schemaVersion + 1},
        );
        final prelaunchSchema = await _tamperBackup(
          backupPath,
          root,
          manifestUpdates: {
            'schemaVersion': AppDatabase.minimumSupportedSchemaVersion - 1,
          },
        );
        final newerFormat = await _tamperBackup(
          backupPath,
          root,
          manifestUpdates: {'format': 99},
        );
        final prelaunchFormat = await _tamperBackup(
          backupPath,
          root,
          manifestUpdates: {'format': 1},
        );

        for (final invalid in <File>[
          tamperedChecksum,
          newerSchema,
          prelaunchSchema,
          newerFormat,
          prelaunchFormat,
        ]) {
          await expectLater(
            service.inspectBackup(invalid.path),
            throwsA(isA<BackupException>()),
          );
        }
      },
    );
"""
text = text[:start] + new_tests + text[end:]
legacy_helper_start = text.index("Future<File> _createFormatOneBackup")
legacy_helper_end = text.index("String _uuid()", legacy_helper_start)
text = text[:legacy_helper_start] + text[legacy_helper_end:]
write(path, text)

# ---------------------------------------------------------------------------
# Permission education is device-local from first production. Remove v1/v2
# sync/bootstrap compatibility while preserving the current v3 serialization.
# ---------------------------------------------------------------------------
write(
    "lib/src/features/permissions/data/permission_education_repository.dart",
    """import 'package:drift/drift.dart';
import '../../../../src/core/database/app_database.dart';
import '../domain/permission_capability.dart';
import '../domain/permission_education_state.dart';

abstract interface class PermissionEducationRepository {
  Future<PermissionEducationDeviceState> loadDeviceState();
  Future<void> saveDeviceState(PermissionEducationDeviceState state);
}

class DriftPermissionEducationRepository
    implements PermissionEducationRepository {
  DriftPermissionEducationRepository(this._database);

  final AppDatabase _database;

  static const String keyV3 = 'permission_education_device_state_v3';

  @override
  Future<PermissionEducationDeviceState> loadDeviceState() async {
    final row = await (_database.select(
      _database.settings,
    )..where((setting) => setting.key.equals(keyV3))).getSingleOrNull();

    if (row != null && row.value.isNotEmpty) {
      return PermissionEducationDeviceState.decode(row.value);
    }

    const initial = PermissionEducationDeviceState(
      showCount: 0,
      source: PermissionEducationSource.firstDashboardVisit,
    );
    await saveDeviceState(initial);
    return initial;
  }

  @override
  Future<void> saveDeviceState(PermissionEducationDeviceState state) async {
    await _database
        .into(_database.settings)
        .insertOnConflictUpdate(
          SettingsCompanion.insert(
            key: keyV3,
            value: state.encode(),
            updatedAt: Value(DateTime.now()),
          ),
        );
  }
}
""",
)

path = "lib/src/core/sync/sync_dtos.dart"
text = read(path)
text = text.replace("  'permission_education_seen',\n", "")
text = text.replace("  'permission_education_seen_v2',\n", "")
text = text.replace(
    "      \"'notification_preferences', 'onboarding_completed', \"\n"
    "      \"'permission_education_seen', 'permission_education_seen_v2', \"\n"
    "      \"'home_location')\",",
    "      \"'notification_preferences', 'onboarding_completed', \"\n"
    "      \"'home_location')\",",
)
write(path, text)

path = "test/user_settings_contract_test.dart"
text = read(path)
old_test = """    test(
      'permission_education_seen_v2 is included in allowedRemoteSettingKeys',
      () {
        expect(
          allowedRemoteSettingKeys.contains('permission_education_seen_v2'),
          isTrue,
        );
      },
    );
"""
new_test = """    test('permission education state is device-local', () {
      for (final key in const <String>[
        'permission_education_seen',
        'permission_education_seen_v2',
        'permission_education_device_state_v3',
      ]) {
        expect(allowedRemoteSettingKeys.contains(key), isFalse);
        expect(() => store.validateUserSettingKey(key), throwsArgumentError);
      }
    });
"""
if old_test not in text:
    raise RuntimeError("user_settings_contract_test.dart: legacy permission test changed unexpectedly")
write(path, text.replace(old_test, new_test, 1))

# Server-side key constraint is production history: add a forward migration,
# never edit an old migration. Existing rows are deleted before tightening the
# check, which is safe for the declared zero-user first-production launch.
write(
    "supabase/migrations/20260814110000_retire_prelaunch_permission_settings.sql",
    """-- First-production baseline: permission education is device-local only.
begin;

delete from public.user_settings
where key in ('permission_education_seen', 'permission_education_seen_v2');

alter table public.user_settings
  drop constraint if exists user_settings_key_check;

alter table public.user_settings
  add constraint user_settings_key_check
  check (key in (
    'theme',
    'app_language',
    'app_language_explicit',
    'theme_time_of_day_enabled',
    'notifications_enabled',
    'notification_preferences',
    'onboarding_completed',
    'home_location'
  ));

notify pgrst, 'reload schema';
commit;
""",
)
write(
    "supabase/tests/database/0016_prelaunch_settings_cleanup.test.sql",
    """begin;

create extension if not exists pgtap with schema extensions;

select plan(2);

select is(
  (
    select count(*)
    from public.user_settings
    where key in ('permission_education_seen', 'permission_education_seen_v2')
  ),
  0::bigint,
  'prelaunch permission education settings are absent'
);

select ok(
  exists (
    select 1
    from pg_constraint
    where conrelid = 'public.user_settings'::regclass
      and conname = 'user_settings_key_check'
      and pg_get_constraintdef(oid) not like '%permission_education_seen%'
  ),
  'user settings constraint rejects retired permission education keys'
);

select * from finish();
rollback;
""",
)

# ---------------------------------------------------------------------------
# Monetization: current RPCs return structured insufficient_points results.
# Remove only the previous-backend exception shim; server point authority,
# idempotency, SSV, and typed shortage behavior remain unchanged.
# ---------------------------------------------------------------------------
path = "lib/src/features/monetization/monetization.dart"
text = read(path)
legacy_block = """    late final Map<String, dynamic> data;
    try {
      data = await client.rpc<Map<String, dynamic>>(
        functionName,
        params: {'p_operation': operation},
      );
    } on PostgrestException catch (error) {
      // Compatibility with the immediately previous backend. Build 44 returns
      // this expected business state as HTTP 200 to avoid warning/error noise.
      if (error.message == 'INSUFFICIENT_POINTS') {
        throw const InsufficientPointsException(balance: 0);
      }
      rethrow;
    }
"""
current_block = """    final data = await client.rpc<Map<String, dynamic>>(
      functionName,
      params: {'p_operation': operation},
    );
"""
if legacy_block not in text:
    raise RuntimeError("monetization.dart: previous-backend compatibility block changed unexpectedly")
write(path, text.replace(legacy_block, current_block, 1))

# ---------------------------------------------------------------------------
# Documentation synchronization.
# ---------------------------------------------------------------------------
path = "docs/permissions.md"
text = read(path)
text = text.replace(
    "- Legacy compatibility: Old clients reading `permission_education_seen_v2` remain supported, but new clients evaluate `v3` device state.",
    "- First-production baseline: prelaunch `permission_education_seen` and `permission_education_seen_v2` account flags are retired. Permission education state is device-local only and is never synchronized.",
    1,
)
write(path, text)

path = "docs/architecture/backup-and-restore.md"
text = read(path)
old = """Drift schema 25 removes the retired task-dependency metadata column. Opening a
schema-24 database restored from an older valid backup runs the forward
migration, discards only that retired link list, and preserves the task and its
remaining metadata. The backup ZIP format itself is unchanged.
"""
new = """The zero-user first-production baseline accepts backup format 2 and Drift schema
25 or newer compatible schemas only. Prelaunch format-1 archives and Drift
schemas 1 through 24 are intentionally rejected instead of being carried into
production. The format version remains independent from the Flutter package and
Drift schema versions, and all archive integrity, path, checksum, staging, and
rollback protections remain mandatory.
"""
if old not in text:
    raise RuntimeError("backup-and-restore.md: historical schema paragraph changed unexpectedly")
text = text.replace(old, new, 1)
text = text.replace("- Which Drift schema versions can be migrated.", "- Which production Drift schema versions are accepted or migrated.")
text = text.replace(
    "Cover valid current and historical archives, corrupted ZIPs, traversal paths, duplicate names, hash mismatch, oversized expansion, unsupported versions,",
    "Cover valid production-baseline and current archives, corrupted ZIPs, traversal paths, duplicate names, hash mismatch, oversized expansion, unsupported or prelaunch versions,",
)
write(path, text)

path = "docs/architecture/data-model.md"
text = read(path)
marker = "## Schema-change procedure\n"
insert = """## First-production local schema baseline

HomePilot's first production launch establishes Drift schema 25 as the minimum
supported local database. Fresh installs create that schema directly. Schemas
1 through 24 were prelaunch development history and are deliberately rejected
rather than upgraded. This baseline does **not** make synchronization metadata
disposable: outbox, cursors, shadows, hydration, account binding, media cleanup,
reminder reconciliation, and other live operational tables remain part of the
current schema and protocol.

After production launch, ordinary schema evolution resumes with forward
migrations from the immediately previous supported production schema.

"""
if marker not in text:
    raise RuntimeError("data-model.md: schema procedure heading missing")
text = text.replace(marker, insert + marker, 1)
write(path, text)

path = "docs/architecture/monetization.md"
text = read(path)
text = text.replace(
    "The Flutter repository maps that\n        payload (and the immediately previous backend's legacy exception during rollout)\n        to a typed shortage.",
    "The Flutter repository maps that payload to a typed shortage.",
)
text = text.replace(
    "The Flutter repository maps that payload (and the immediately previous backend's legacy exception during rollout) to a typed shortage.",
    "The Flutter repository maps that payload to a typed shortage.",
)
write(path, text)

path = "docs/development/testing.md"
text = read(path)
text = text.replace(
    "Use temporary Drift databases to verify queries, transactions, schema migrations, outbox behavior, reminder snapshots, cleanup, and restart persistence. Migration tests must begin from historical schema fixtures rather than only creating the latest schema.",
    "Use temporary Drift databases to verify queries, transactions, schema compatibility, outbox behavior, reminder snapshots, cleanup, and restart persistence. For the zero-user first-production baseline, tests prove fresh schema-25 creation and rejection of prelaunch schemas 1 through 24. Future production schema changes must test migration from the immediately previous supported production schema.",
)
text = text.replace(
    "Test valid current/historical backups, unsupported versions,",
    "Test valid schema-25/current backups, rejected prelaunch formats/schemas, unsupported newer versions,",
)
text = text.replace(
    "Schema migration coverage must preserve tasks and remaining metadata while removing retired dependency links.",
    "Local database compatibility coverage must create the complete schema-25 sync/runtime baseline and reject prelaunch schemas rather than executing retired conversion code.",
)
write(path, text)

path = "AGENTS.md"
text = read(path)
marker = "## Synchronization rules\n"
insert = """### First-production baseline exception

Before the first public production launch, HomePilot intentionally establishes
Drift schema 25 and backup format 2 as compatibility floors because there are no
production users to migrate. Prelaunch schemas 1 through 24 and backup format 1
are unsupported. Do not reintroduce those historical converters. After the
first production release, the ordinary forward-migration requirements above
apply to every shipped schema change.

"""
if marker not in text:
    raise RuntimeError("AGENTS.md: synchronization heading missing")
text = text.replace(marker, insert + marker, 1)
write(path, text)

path = "docs/backend/supabase.md"
text = read(path)
marker = "## Deployment\n"
insert = """## First-production settings cleanup

The forward migration
[`20260814110000_retire_prelaunch_permission_settings.sql`](../../supabase/migrations/20260814110000_retire_prelaunch_permission_settings.sql)
removes the prelaunch `permission_education_seen` and
`permission_education_seen_v2` user-setting keys and tightens the database
constraint to the current client allowlist. Permission education v3 is
intentionally device-local. This is a forward migration; prior migration files
remain immutable production history and are not squashed or repaired.

"""
if marker not in text:
    raise RuntimeError("supabase.md: deployment heading missing")
text = text.replace(marker, insert + marker, 1)
write(path, text)

path = "docs/backend/migrations-and-functions.md"
text = read(path)
marker = "## Destructive changes\n"
insert = """## Zero-user first-production cleanup

`20260814110000_retire_prelaunch_permission_settings.sql` is a narrow forward
cleanup for the declared zero-user launch. It deletes only the retired
prelaunch permission-education account flags and updates the `user_settings`
key constraint. It does not squash, edit, repair, or renumber existing Supabase
migration history, and it does not authorize hosted deployment while
production containment is active.

"""
if marker not in text:
    raise RuntimeError("migrations-and-functions.md: destructive changes heading missing")
text = text.replace(marker, insert + marker, 1)
write(path, text)

path = "docs/development/github-actions-supply-chain.md"
text = read(path)
text = text.replace(
    "| `actions/checkout` | `v6` | [`v6.1.0`](https://github.com/actions/checkout/releases/tag/v6.1.0) | `d23441a48e516b6c34aea4fa41551a30e30af803` |",
    "| `actions/checkout` | `v6.1.0` | [`v7.0.1`](https://github.com/actions/checkout/releases/tag/v7.0.1) | `3d3c42e5aac5ba805825da76410c181273ba90b1` |",
)
text = text.replace(
    "| `actions/setup-node` | `v6` | [`v6.5.0`](https://github.com/actions/setup-node/releases/tag/v6.5.0) | `249970729cb0ef3589644e2896645e5dc5ba9c38` |",
    "| `actions/setup-node` | `v6.5.0` | [`v7.0.0`](https://github.com/actions/setup-node/releases/tag/v7.0.0) | `820762786026740c76f36085b0efc47a31fe5020` |",
)
text = text.replace(
    "| `actions/upload-artifact` | `v4` | [`v4.6.2`](https://github.com/actions/upload-artifact/releases/tag/v4.6.2) | `ea165f8d65b6e75b540449e92b4886f43607fa02` |\n",
    "",
)
text = text.replace(
    "| `actions/upload-artifact` | `v6` | [`v6.0.0`](https://github.com/actions/upload-artifact/releases/tag/v6.0.0) | `b7c566a772e6b6bfb58ed0dc250532a479d7789f` |\n",
    "",
)
text = text.replace(
    "The release review found no reason to change the already selected major\nversions. Relevant upstream notes that future reviewers must preserve include:\n",
    "The 2026-08-14 first-production modernization advanced `checkout` to v7.0.1, `setup-node` to v7.0.0, and all current artifact uploads to v7.0.1 after reviewing their upstream release notes. Other reviewed action majors remained current. Relevant upstream notes that future reviewers must preserve include:\n",
)
text = text.replace(
    "- `actions/checkout@v6.1.0` changes the safer `pull_request_target` checkout\n  default. HomePilot does not use `pull_request_target`.\n",
    "- `actions/checkout@v7.0.1` retains the safer `pull_request_target` checkout behavior and includes dependency/security maintenance. HomePilot does not use `pull_request_target`.\n",
)
text = text.replace(
    "- `actions/setup-node@v6.5.0` and `actions/setup-java@v5.7.0` include upstream\n  dependency/audit fixes; the Java release also deprecates legacy Adopt\n  distributions, while HomePilot uses Temurin.\n",
    "- `actions/setup-node@v7.0.0` moves to the current ESM/cache implementation and includes cache-safety guidance; `actions/setup-java@v5.7.0` includes upstream dependency/audit fixes and deprecates legacy Adopt distributions, while HomePilot uses Temurin.\n",
)
write(path, text)

path = "docs/operations/release-runbook.md"
text = read(path)
text = text.replace(
    "without changing their existing major versions",
    "at the latest reviewed stable compatible majors",
)
write(path, text)

path = "CHANGELOG.md"
text = read(path)
marker = "## Unreleased\n"
entry = """
### First-production modernization

- Raised the supported Flutter toolchain to 3.47.0 and Deno to 2.9.5, upgraded direct Flutter/Dart and Node dependencies to the latest stable compatible releases, refreshed lockfiles, and advanced reviewed GitHub Actions pins including checkout/setup-node and artifact upload without weakening the full-SHA supply-chain policy.
- Established Drift schema 25 and backup format 2 as the zero-user first-production compatibility floor. Removed the unused v1-v24 local migration chain and format-1 restore path while preserving the current outbox, cursor, shadow, hydration, account-binding, media-cleanup, reminder-reconciliation, backup-integrity, and restore-rollback architecture.
- Retired prelaunch synchronized permission-education flags in favor of the existing v3 device-local state using a new forward Supabase migration and database contract test; existing Supabase migration history remains append-only.
- Removed the previous-backend `INSUFFICIENT_POINTS` exception shim now that charged creation uses the structured server-authoritative shortage result.

"""
if marker not in text:
    raise RuntimeError("CHANGELOG.md: Unreleased heading missing")
text = text.replace(marker, marker + entry, 1)
write(path, text)

# Guardrails: these are live protocols, not prelaunch compatibility.
for protected in [
    "depends_on_operation_id",
    "release_attempt_id",
    "account-deletion-status",
    "offline_mutation_queue",
]:
    if not any(protected in p.read_text(encoding="utf-8", errors="ignore") for p in ROOT.rglob("*.*") if p.is_file() and ".git" not in p.parts):
        raise RuntimeError(f"protected live protocol marker disappeared: {protected}")

print("Zero-user modernization source edits staged successfully.")
